name: libyaml

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ head, 3.1, "3.0", 2.7, 2.6, 2.5, 2.4 ]
        libyaml: [0.1.7, 0.2.5]
        libyaml-prefix: [/tmp/local, '']

    steps:
      - name: Install libraries
        run: sudo apt install haveged
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set up libyaml ${{ matrix.libyaml }}
        run: |
          wget https://pyyaml.org/download/libyaml/yaml-${{ matrix.libyaml }}.tar.gz
          tar xzf yaml-${{ matrix.libyaml }}.tar.gz
          cd yaml-${{ matrix.libyaml }}
          ./configure --prefix=${{ matrix.libyaml-prefix }}
          make
          make install
        if: ${{ matrix.libyaml-prefix != '' }}
      - name: Install dependencies
        run: bundle install
      - name: Compile
        run: >-
          rake compile --
          ${{ matrix.libyaml-prefix != '' && '--with-libyaml-dir='
            || '--with-libyaml-source-dir'
          }}${{ matrix.libyaml-prefix }}
      - name: Run test
        run: rake
      - name: Install gem
        run: |
          rake build
          gem install pkg/psych-*.gem -- --with-libyaml-dir=${{ matrix.libyaml-prefix }}
        if: ${{ matrix.ruby != 'head' && matrix.ruby != '3.1' && matrix.libyaml-prefix != '' }}
