name: ubuntu-jruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ jruby, jruby-head ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: gem install ruby-maven power_assert test-unit rake-compiler 
      - name: compile
        run: rake compile
      - name: test
        continue-on-error: true
        run: rake test
